### ISSUE TITLE
采集其他的接口他不会封你吗？

### ISSUE THREAD

**Issue by Guidozijef** [mengkunsoft/wallpaper#1]
我找了很多的Api音乐接口，发的ajax请求很多都不久就被封了，报403错误，你如何解决这快的问题？或者有没有音乐的api接口推荐一下？谢谢

**Comment by mengkunsoft** [comment]
参考 https://github.com/metowolf/Meting

**Comment by Guidozijef** [comment]
> 参考https://github.com/metowolf/Meting

我只会python语言不会php语言呀
